# Generated by Django 6.1 on 2026-08-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_alter_endpoint_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='body',
            new_name='payload',
        ),
    ]
