# Generated by Django 6.1 on 2026-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_rename_body_requestlog_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='method',
            field=models.CharField(max_length=10),
        ),
    ]
