# Generated by Django 6.1 on 2026-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_alter_requestlog_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
