# Generated by Django 6.1 on 2026-09-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_endpoint_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
