# Generated by Django 6.1 on 2026-09-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_endpoint_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='client_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='content_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
