# Generated by Django 6.1 on 2026-09-14 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0009_alter_requestlog_replay_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='mock_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='mock_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.CheckConstraint(condition=models.Q(('mock_status__gte', 100), ('mock_status__lte', 599)), name='valid_http_status_code'),
        ),
    ]
