# Generated by Django 6.1 on 2026-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0010_endpoint_mock_enabled_endpoint_mock_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='mock_body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
