# Generated by Django 6.1 on 2026-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0011_endpoint_mock_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='revoked',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
