# Generated by Django 6.1 on 2026-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0012_alter_endpoint_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
